name: 'Cache Manager'
description: 'Ação centralizada para gerenciamento de cache com chaves hierárquicas e logging aprimorado.'
inputs:
  key:
    description: 'Componente principal da chave de cache (ex: hash do lockfile).'
    required: true
  path:
    description: 'Caminho(s) a serem cacheados.'
    required: true
  prefix:
    description: 'Prefixo para a chave de cache (ex: pnpm, go, nx).'
    required: true
  lookup-only:
    description: 'Se true, apenas restaura o cache, não salva no final.'
    required: false
    default: 'false'
outputs:
  cache-hit:
    description: 'Indica se o cache foi encontrado com a chave principal.'
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Log Cache Key Details
      shell: bash
      run: |
        echo "🔹 Cache Manager:"
        echo "   Prefix: ${{ inputs.prefix }}"
        echo "   Key: ${{ inputs.key }}"
        echo "   Path: ${{ inputs.path }}"
        echo "   Lookup-only: ${{ inputs.lookup-only }}"

    - name: Manage Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}
        key: ${{ runner.os }}-${{ inputs.prefix }}-v3-${{ inputs.key }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.prefix }}-v3-
        enableCrossOsArchive: true
        lookup-only: ${{ inputs.lookup-only }}

    - name: Log Cache Status
      shell: bash
      run: |
        if [ "${{ steps.cache.outputs.cache-hit }}" = "true" ]; then
          echo "   ✅ Cache hit para a chave principal."
        else
          echo "   ℹ️ Cache miss. Buscando por chaves de restauração..."
        fi
