name: 'Restore Nx cache'
description: 'Restore Nx cache for faster builds and tests'
inputs:
  cache-key:
    description: 'Custom cache key suffix (default: github.sha)'
    required: false
    default: ''
outputs:
  cache-hit:
    description: 'Whether Nx cache was hit'
    value: ${{ steps.nx-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Set cache key
      id: cache-key
      shell: bash
      run: |
        if [ -n "${{ inputs.cache-key }}" ]; then
          echo "key=${{ inputs.cache-key }}" >> $GITHUB_OUTPUT
        else
          # Fallback para o SHA do commit de merge em um PR
          echo "key=${{ github.event.pull_request.merge_commit_sha || github.sha }}" >> $GITHUB_OUTPUT
        fi

    - name: Cache Nx
      id: nx-cache
      uses: ./.github/actions/cache-manager
      with:
        path: .nx/cache
        prefix: nx
        key: ${{ steps.cache-key.outputs.key }}

    - name: Nx cache status
      shell: bash
      run: |
        if [ "${{ steps.nx-cache.outputs.cache-hit }}" = "true" ]; then
          echo "✅ Nx cache hit - builds and tests will be faster"
        else
          echo "ℹ️ Nx cache miss - will build from scratch"
        fi
