name: 'Setup Playwright with optimized caching'
description: 'Setup Playwright with system dependencies and browser caching'
inputs:
  install-browsers:
    description: 'Whether to install browsers (default: true)'
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: 'Whether Playwright cache was hit'
    value: ${{ steps.playwright-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Cache Playwright Browsers
      id: playwright-cache
      uses: ./.github/actions/cache-manager
      with:
        path: |
          ~/.cache/ms-playwright
        prefix: playwright
        key: ${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Playwright Browsers
      if: inputs.install-browsers == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🔧 Instalando browsers do Playwright..."
        npx playwright install chromium --with-deps
        echo "✅ Browsers do Playwright instalados"

    - name: Playwright cache status
      shell: bash
      run: |
        if [ "${{ steps.playwright-cache.outputs.cache-hit }}" = "true" ]; then
          echo "✅ Playwright cache hit - browsers restored from cache"
        else
          echo "ℹ️ Playwright cache miss - installing browsers from scratch"
        fi
