name: Reusable Quality Gate

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

env:
  NODE_VERSION: '20'
  GO_VERSION: '1.23'
  PNPM_VERSION: '9'

jobs:
  setup:
    uses: ./.github/workflows/_reusable-setup.yml

  quality-gate:
    name: Quality Gate & Coverage
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate Coverage (TS/JS)
        run: pnpm nx affected -t test --coverage --parallel=3
      
      - name: Generate Coverage (Go)
        run: pnpm nx affected -t coverage --parallel=2
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
