name: Reusable Setup

on:
  workflow_call:
    inputs:
      fetch-depth:
        type: number
        default: 0
      install-dependencies:
        type: boolean
        default: true
      setup-go:
        type: boolean
        default: true
    outputs:
      cache-hit-pnpm:
        value: ${{ jobs.setup.outputs.cache-hit-pnpm }}
      cache-hit-nx:
        value: ${{ jobs.setup.outputs.cache-hit-nx }}

env:
  NODE_VERSION: '20'
  GO_VERSION: '1.23'
  PNPM_VERSION: '9'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit-pnpm: ${{ steps.cache-pnpm.outputs.cache-hit }}
      cache-hit-nx: ${{ steps.cache-nx.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
          filter: tree:0

      - name: Cache pnpm store
        id: cache-pnpm
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Cache Nx
        id: cache-nx
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml', 'nx.json') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml', 'nx.json') }}-
            nx-${{ runner.os }}-

      - name: Cache Go modules
        if: ${{ inputs.setup-go }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum', '**/go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            dist/
            apps/*/dist/
            libs/*/dist/
          key: build-${{ runner.os }}-${{ hashFiles('**/package.json', '**/tsconfig*.json') }}-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-${{ hashFiles('**/package.json', '**/tsconfig*.json') }}-
            build-${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup Go
        if: ${{ inputs.setup-go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            apps/user-go-service/go.sum
            libs/user-go/go.sum

      - name: Install dependencies
        if: ${{ inputs.install-dependencies }}
        run: pnpm install --frozen-lockfile

      - name: Set up Nx SHAs
        uses: nrwl/nx-set-shas@v4
