name: Release Validation

on:
  pull_request:
    branches: ['release/**']
  push:
    branches: ['release/**']

permissions:
  contents: read
  pull-requests: write

env:
  NODE_VERSION: '20'
  GO_VERSION: '1.23'
  PNPM_VERSION: '9'

jobs:
  validate:
    name: Basic Validation
    uses: ./.github/workflows/reusable-validate.yml

  quality-gate:
    name: Quality Gate & Coverage
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - run: pnpm install --frozen-lockfile
      
      - uses: nrwl/nx-set-shas@v4
      
      - name: Generate Coverage (TS/JS)
        run: pnpm nx affected -t test --coverage --parallel=3
      
      - name: Generate Coverage (Go)
        run: pnpm nx affected -t coverage --parallel=2
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release-dry-run:
    name: Release Dry Run
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      
      - name: Validate Release Consistency
        run: |
          chmod +x scripts/validate-release-consistency.sh
          ./scripts/validate-release-consistency.sh
      
      - name: Nx Release Dry Run
        run: pnpm nx release --dry-run
