name: Release Validation

on:
  pull_request:
    branches: ['release/**']
  push:
    branches: ['release/**']

permissions:
  contents: read
  pull-requests: write

env:
  NODE_VERSION: '20'
  GO_VERSION: '1.23'
  PNPM_VERSION: '9'

jobs:
  validate:
    uses: ./.github/workflows/_reusable-validate.yml

  quality-gate:
    needs: validate
    uses: ./.github/workflows/_reusable-quality-gate.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release-dry-run:
    needs: quality-gate
    uses: ./.github/workflows/_reusable-release-steps.yml
    with:
      dry-run: true
