name: Release Validation

on:
  pull_request:
    branches: [main]

jobs:
  release-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: |
            apps/user-go-service/go.sum
            libs/user-go/go.sum

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate Go dependencies sync
        run: ./scripts/sync-go-versions.sh

      - name: Build affected projects
        run: pnpm nx affected -t build --parallel=3

      - name: Test affected projects
        run: pnpm nx affected -t test --parallel=3

      - name: Lint affected projects
        run: pnpm nx affected -t lint --parallel=3

      - name: Check module boundaries
        run: pnpm nx affected -t check-boundaries --parallel=3

      - name: Release dry-run
        run: pnpm nx release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
