name: Release Validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  dry-run:
    name: Validate Release Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        id: node-pnpm-setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GL_TOKEN }}

      - name: Setup Go
        uses: ./.github/actions/setup-go
        with:
          has-go-changes: 'true'
        id: go-setup

      - name: Restore Nx cache
        uses: ./.github/actions/restore-nx-cache
        id: nx-cache

      - name: Dry-run release versioning
        run: pnpm nx release version --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
